#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
# AI Team Framework — New Deployment Script
# Scaffolds a fresh OWNER_CONTEXT.md for a new business
# and optionally clears agent memory files for a clean start
# ─────────────────────────────────────────────────────────────
# Usage:
#   ./scripts/new-deployment.sh "My Business Name"
#   ./scripts/new-deployment.sh "My Business Name" --reset-memory
# ─────────────────────────────────────────────────────────────

set -euo pipefail

AGENTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$AGENTS_DIR/.." && pwd)"
MEMORY_DIR="$AGENTS_DIR"
TEMPLATE="$MEMORY_DIR/OWNER_CONTEXT.template.md"
CONTEXT="$MEMORY_DIR/OWNER_CONTEXT.md"
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M")

BUSINESS_NAME="${1:-Unnamed Business}"
RESET_MEMORY=false
if [[ "$2" == "--reset-memory" ]]; then
  RESET_MEMORY=true
fi

echo ""
echo "╔══════════════════════════════════════╗"
echo "║      New Deployment: $BUSINESS_NAME"
echo "╚══════════════════════════════════════╝"
echo ""

# ─────────────────────────────────────────────
# Archive existing context if present
# ─────────────────────────────────────────────
if [ -f "$CONTEXT" ]; then
  ARCHIVE_DIR="$MEMORY_DIR/archive"
  mkdir -p "$ARCHIVE_DIR"
  ARCHIVE_NAME="OWNER_CONTEXT_${TIMESTAMP}.md"
  cp "$CONTEXT" "$ARCHIVE_DIR/$ARCHIVE_NAME"
  echo "► Archived existing context → memory/archive/$ARCHIVE_NAME"
fi

# ─────────────────────────────────────────────
# Create fresh OWNER_CONTEXT.md from template
# Inject business name at the top
# ─────────────────────────────────────────────
cp "$TEMPLATE" "$CONTEXT"

# Prepend deployment header
HEADER="# DEPLOYMENT: $BUSINESS_NAME
# Created: $(date +"%Y-%m-%d")
# Generated by: scripts/new-deployment.sh
# ─────────────────────────────────────────────
"
echo "$HEADER" | cat - "$CONTEXT" > "$CONTEXT.tmp" && mv "$CONTEXT.tmp" "$CONTEXT"
echo "► Created fresh OWNER_CONTEXT.md ✓"

# ─────────────────────────────────────────────
# Optionally reset agent memory files
# ─────────────────────────────────────────────
AGENTS=(conductor compass forge books prophecy engine pulse kat lock closer)

if [ "$RESET_MEMORY" = true ]; then
  echo "► Resetting agent memory files..."

  ARCHIVE_DIR="$MEMORY_DIR/archive/memory_${TIMESTAMP}"
  mkdir -p "$ARCHIVE_DIR"

  for agent in "${AGENTS[@]}"; do
    MEM_FILE="$MEMORY_DIR/${agent}.memory.md"
    if [ -f "$MEM_FILE" ] && [ -s "$MEM_FILE" ]; then
      cp "$MEM_FILE" "$ARCHIVE_DIR/${agent}.memory.md"
    fi
    UPPER=$(echo "$agent" | tr '[:lower:]' '[:upper:]')
    cat > "$MEM_FILE" <<EOF
# ${UPPER} MEMORY
# Deployment: $BUSINESS_NAME
# Reset: $(date +"%Y-%m-%d")
Last Updated: —
Session Count: 0

## CURRENT STATE
Not yet initialized. New deployment: $BUSINESS_NAME.

## RECENT DECISIONS
None yet.

## LESSONS LEARNED
None yet.

## OPEN ITEMS
None yet.

## NEXT RECOMMENDED ACTION
Run first session: /nexus  Read OWNER_CONTEXT.md. Give me a status report.
EOF
  done
  echo "  Agent memory files reset ✓"
  echo "  Previous memory archived → memory/archive/memory_${TIMESTAMP}/"
fi

# ─────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════╗"
echo "║         Deployment Ready ✓           ║"
echo "╚══════════════════════════════════════╝"
echo ""
echo "Next steps:"
echo ""
echo "  1. Fill in your context:"
echo "     $CONTEXT"
echo ""
echo "  2. Restart Claude Desktop"
echo ""
echo "  3. Start session:"
echo "     /nexus  Read memory/OWNER_CONTEXT.md. Give me a status report."
echo ""
echo "To reset memory on next deployment:"
echo "  ./scripts/new-deployment.sh \"Business Name\" --reset-memory"
echo ""
